(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/aaa.jpg?1467460044886", id:"aaa"},
		{src:"images/aas.png?1467460044886", id:"aas"},
		{src:"images/asdgasdgasdfgsdg.png?1467460044886", id:"asdgasdgasdfgsdg"},
		{src:"images/asdgasfhaerfghafh.png?1467460044886", id:"asdgasfhaerfghafh"},
		{src:"images/ddd.png?1467460044886", id:"ddd"},
		{src:"images/eee.png?1467460044886", id:"eee"},
		{src:"images/fff.png?1467460044886", id:"fff"},
		{src:"images/ggg.png?1467460044886", id:"ggg"},
		{src:"images/iii.png?1467460044886", id:"iii"},
		{src:"images/mmm.png?1467460044886", id:"mmm"},
		{src:"images/nnnn.png?1467460044886", id:"nnnn"},
		{src:"images/ooo.png?1467460044886", id:"ooo"},
		{src:"images/qqq.png?1467460044886", id:"qqq"},
		{src:"images/rrr.png?1467460044886", id:"rrr"},
		{src:"images/sss.png?1467460044886", id:"sss"},
		{src:"images/uuu.png?1467460044886", id:"uuu"},
		{src:"images/www.png?1467460044886", id:"www"}
	]
};



// symbols:



(lib.aaa = function() {
	this.initialize(img.aaa);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,414,392);


(lib.aas = function() {
	this.initialize(img.aas);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,90,92);


(lib.asdgasdgasdfgsdg = function() {
	this.initialize(img.asdgasdgasdfgsdg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,437,176);


(lib.asdgasfhaerfghafh = function() {
	this.initialize(img.asdgasfhaerfghafh);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,426,147);


(lib.ddd = function() {
	this.initialize(img.ddd);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,89,93);


(lib.eee = function() {
	this.initialize(img.eee);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,33,59);


(lib.fff = function() {
	this.initialize(img.fff);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,701,334);


(lib.ggg = function() {
	this.initialize(img.ggg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,169,173);


(lib.iii = function() {
	this.initialize(img.iii);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,248,26);


(lib.mmm = function() {
	this.initialize(img.mmm);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,124,26);


(lib.nnnn = function() {
	this.initialize(img.nnnn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,269,273);


(lib.ooo = function() {
	this.initialize(img.ooo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,367,373);


(lib.qqq = function() {
	this.initialize(img.qqq);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,114,168);


(lib.rrr = function() {
	this.initialize(img.rrr);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,57,77);


(lib.sss = function() {
	this.initialize(img.sss);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,179,185);


(lib.uuu = function() {
	this.initialize(img.uuu);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,58);


(lib.www = function() {
	this.initialize(img.www);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,42,56);


(lib.Символ69 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.4,-11,0.5,11.1).s().p("Ag+BdIgEgBIgEgFIgEgGIgBgEIAAgFIABgQIgDgsIABgLIgBgqIgBgHQgBgBAAgBQgBgBAAAAQAAAAgBAAQgBgBAAABIgFAAIgGgEIgFABIgDAAIgIgDIgCgEIgBgFQAAgGAFgDQAEgCAGAAIBJgEIAEABIAEACIABAEIABABIABACIAAADIgBACIgIAGIgEABIgHADIgCACIgGAIIgDAEIgBAYIADAiIAAAKIABAFQAAAAAAABQABAAAAAAQAAABABAAQAAAAABAAQADAAAFgGIAbgkQAFgDACgGIAhgpIAIgGQAEgDABgFIADgEIAFgFIAFgGQACgEAEAAQAGAAACACQADADABAGIgDApIABALIAAAEQgCADABADIAAAWIADALIAAAFIAAAEIAAAEIAAAMIgBAGIAAADIACADIACADIAEACIASABIAEACQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAFIgBADQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgGgBIgLAAIgHACQgDACgGAAIgLABIgGADIgSgCIgfABIgDAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFADgCQADgDAFgBIAUgFQAFgCADgDQACgCAAgGIgBgOIABgRIgBgqQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIgFACIgFAFIgFAJIgWAbIgLAOIgLAOIgPAaIgSAUQAAACgFAAg");
	this.shape.setTransform(-15.7,3.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.1,-3.6,0.2,3.7).s().p("AgbBSQAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgDAEgDIANgLQADgDgBgEQgCgEABgDIAAgEIgChDIgEgIIADgOIgBgJIgDgGIgDgBIgIgBIgDgBQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIgCgHIAAgDIACgDIAQAAIADAAIAGACIAEgBIAJgCIADAAIADgBIABgBIAMABIADAAIADACIADACIACAEIABAEQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIgQAFQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAAAIABAVIADALIgCANIAGAcIAAAMIgCAIIABAHIgCAEQgBABAAAGIABADIACACIAEACIAIADQAIADABAIQAAAEgFACQgFADgFAAIgQAAIgIgCIgWAGg");
	this.shape_1.setTransform(-31.9,4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.2,-6.8,0.3,6.6).s().p("AgxBTIAAgBIgCgBIgDAAIgCAAQgEgBgCgBIgBgEIABgIQABgEAEAAIAFAAIANgDIACgBIABgDIgBgEQAAgBAAAAQABgBAAAAQAAgBAAAAQAAAAAAgBIgBgCIgBgHIACgIIAAgOIAAgBIAAgCIgCg7QABgIgFgCQgEgEgGAAIgKgCQgFgBABgHIABgCIADgFIAFgEIAGgBIAHACIAUgBIADgBIAOAAIAEABQACABAEgCIALgBIAIABIAEABQABABAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgBAKQgCAFgGAAIgQADQgCAAgBADIgDAEIgEAGIAAADIgBAVIABAEIAAAKIABABIASgBIAVABIAOAEIAEADQADAAADABIAFAHIAFAPIAAAVQAAAFgDAFIgEAIIgCACIgEADQgIAGgMAEQgMAEgMAAIgmABIgIgBIgHACgAgEAKIgEAIIgCANIABAUIABACIACADIADADIADACIAHgCIAOgFIAJgEIAGgHQADgEgBgDIgBgRQAAgEgEgCIgHgEIgJgBIgRAAQgCAAgCACg");
	this.shape_2.setTransform(-42.1,5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.1,-6.5,0.4,6.4).s().p("AgtBSIgCgBIgDgBIgCAAQgEABgCgCIgCgDIABgJQACgEAEgBIAFAAIANgCIABgBIABgDIgBgEQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBgBAAIgBgCIAAgHIABgHIAAgOIADgPIAAgCIgBAAIAAgBIABgLIgBgJIACgLQAAgIgDgFIgHgHIgXgLQgDgCgBgEQAAAAABgBQAAAAAAgBQAAAAAAgBQABgBAAAAIAFgEIAKgDIAGAAIAMgDIAXAAIAEABIAWABQAIACAHAEQAHADAGAGQAGAHAEAIIABAPQABAFgDAFIgKAPIgCAEIABADIAHADQACAAADADIAFAGIAEAIIABAQIgBAOIgCAGIgCADIgCAFIgCACIgEACQgJAHgKAFQgLAEgMAAIgkABIgIgBIgCABIgFABIgFAAIAAgBgAAAANIgEAGIgCAIIABAYIAAACIACADIADADIADACIAGgCIAMgFIAIgFIAGgHQADgEgCgEIAAgJIAAgCIAAgCQgBgEgCgCIgHgEIgJgCIgNAAQgEAAAAAEgAADg2IgDABIgEAGIgCAFIgBAGIABASIADAKIADADIAGABIAEgCIAIgDIAHgGQACgCAAgDIAAgQIgCgGIgHgGIgHgFIgGgCIgCABg");
	this.shape_3.setTransform(-56.3,5.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-4.9,0.2,5,-0.2).s().p("AgOAWIgFAAIgEgCIgEgDIgFgCIgEgCIgEgFIgCgFIgEgDIgCgGQAAgIAFgEQAFgEAIgBIAIABQAEABAAAEIAAACIgBACIABACIABACIgBABIAAABIACAHIAFADIAIADIAFACIANgBIAHgCQADgBADgEIAEgFIAEgPIgBgBIABAAQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIADAAIAEABIADAIIgBACIgBAGIgBADIgBACIgCADIgCADIgCADIgDAEIgDACIgTAKIgSACg");
	this.shape_4.setTransform(51.9,-11.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.4,-11,0.5,11.1).s().p("AhCBbIgEgFIgEgFIgBgEIAAgFIABgQIgDgsIABgLIgBgqIgBgHQgCgEgCAAIgFAAIgGgDIgFAAIgDAAIgDAAIgFgDIgCgEIgBgEQAAgGAFgDQAEgDAGAAIBJgEIAEABIAEADIABAEIABABIABACIAAADIgBACIgIAFIgLAFIgCACIgGAIIgDADIgBAZIADAiIAAAJIABAFQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQADAAAFgHIAbgjQAFgEACgFIAhgpIAIgGQAEgDABgGIADgEIAFgEIAFgHQACgDAEAAQAGgBACADQADADABAFIgCAiIgBAIIABAKIAAAFQgCACABADIAAAXIADALIAAAFIAAAEIAAADIAAAMIgBAHIAAACIACAEIACADIAEABIASACIAEABQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAAFIgBAEQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAIgGAAIgLAAQgEAAgDACQgDACgGAAIgLABQgDAAgDACIgSgBIgfABIgDgBQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgEADgDQADgCAFgBIAUgFQAFgCADgDQACgDAAgFIgBgPIABgQIgBgqQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIgFADIgFAFIgFAJIgWAbIgLANIgLAOIgPAaIgSAUQAAACgFABIgHAAg");
	this.shape_5.setTransform(51.6,1.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.4,-8.5,0.2,8.4).s().p("AhJBXIgHgBQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQgBgFADgEQAEgEAFAAIAGgBIACgCIAJgIIAmhpIAEgVIAEgLIAIgIIAEAAQAEAAADADIAFAHIAEAJIAEAUIAFAIQADAGAAAFIAdBUQADAFAEAAIACABIACAAIAAABIABAAIADAAIADABIADADIACAEQAAAFgEADQgEACgFABIguAAIgIACIgFgBQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgFADgCIAQgJQADgBAAgFIgBgEIgBgGIgDgHQgBgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAABIgDgNIgEgEQgCgCgDABIgMABIgIABIgDACQgDACgBADIAAAHIgFALIgDAKQABAEACABIAEADIAEAEQACABAAAGIgBADIgCACIgEAAIgCAAIgBABIgBABIgDgBIgMgBIgSADIgDABIgBABIgBAAgAAAggIgCAIIgCAKIgCAJIAAAFQAAAAAAABQAAAAABAAQAAABABAAQABABABAAIAKABIAEgCQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAIgCgHIgCgGIAAgNIgCgEIgDgDQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAABAAAAg");
	this.shape_6.setTransform(31.7,1.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.1,-6.7,0.4,6.3).s().p("AgyBTIgFgCIgEgDIgBgGIAAgFIABgFIACgEQACgCAEAAIAEACIALgBQAHAAAAgIIAAgJIABgLIgCgGIABgHIgBgOIABgCQACgBgBgGIgBgQIgBgFQgBgCgBgEIAAgIIABgHIABgEQAAgEgDgDQgEgEgGAAIgHAAIgLgDQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAIABgFIADgEIADgCIAEgBIACAAIADADIAwgCIAYAEIAIgBQAJAAAFAFQAGAGADAIQAEAHADAIIABANIAAAKIgCAMQgCAHgFACQgEAGgGABIgIAEIgDABIgDABIgGAAIgHgBIgHgDQgCgCAAgEQgBgDADAAIAOgEQAEgCADgDQADgDADgHQACgGgBgMIAAgDIgCgFIgHgFIgKgFIgOgDIgFABIgBABIgCACIgBADIAAACIADBDIABANIgBAMIAAAFQAAAHAEADQAEACAFgBIAKABQAEABAAAEIAAAHIgCADIgDADIgDACIgFABIgNgEIgRABIgbAFg");
	this.shape_7.setTransform(15.6,2.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.1,-6.3,0.3,6).s().p("AgxBSIgDgCIgDgEIgBgEQAAgHADgCIAMgJQADgDABgIIAAgEIABgDIABgFIgDhKQABgJgEgCQgDgDgFgBIgHgCQgEgBABgHIAAgDIABgEIACgDQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIADABIAIABIATgEIASADIACAAIABAAIABAAIAhgCIAQACIAEAJIAGAiQAAAAAAABQAAAAAAABQAAAAgBABQgBAAAAAAIgFADQgFAAgDgEQgCgEgFgDIgTgMIgDgCIgQABQAAAAAAAAQAAAAAAAAQgBAAAAABQgBAAAAABIgDADIgDAIIAAAQIACAGIgDATIAFAjIgCAJQAAAGAEADQACAEAGgBIAIAAIADABIALAGIgCAGQAAAEgDACQgEAEgEAAIg9ACg");
	this.shape_8.setTransform(2.6,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63,-13.9,126.1,27.8);


(lib.Символ68 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.7,-10.9,0.1,10.6).s().p("AhiBnQgGgGgCgGQgBgNAGgJQAGgIALgDIAEAAIAFABIADADIAGABIAUgHIAEgFIAIgcIACgPIAAgcIgBgHIABgTIADgHIgDgHIAAgQQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAgBAAIgTgBQgEgBgBgEQAAgGAEgGQAFgGAFAAIAPgDIAJgBIAQADIAGgBIBRgBIAJABIAHAFQADADAAAEIAAADIgCAEIgUAFIgEAJIAAADQgCAKABAFIACAHIgCANIADASIgDANIACA9QgBADACAFQAAAEAFADIAWAIQAEACAAACIAAAFIgEADIgFADIgpACIgQgDIgLAEIgDAAIgJgDIgCgEQAAgEAEgDIARgOQADgFAAgJIgFiBIgCgHQgCgDgDAAIgWACQgGACgBAEIgBAMIACAYIgDA2IgIAYIgEAKIgFAHQAAAGgDAEIgMAMQgFAEgCAGQgDAFgFAAQgEABgBACIgFAEIgGACIgSAFQgHAAgHgFg");
	this.shape.setTransform(-13.9,0.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.3,-10.1,0.5,10.1).s().p("AABBkIgDABIgTAAIgngQQgKgFgGgLIgQglQgGgTgBgQIABgMIAFgOIACgLIAGgQIAIgNIAJgMQAFgFAEAAIAJgEIAJgCIAPgGIAHgBIAWgBIANADIAHgBIAPAFIAFADIAMAEQAHACAFAEIAMARQANAKAEAJQADAJABAIIAAAfIgCAMIgSAqQgDAIgFAFIgeAXQgHAGgLABgAgkg+QgGAIgEAKIgKAiIABAaQAAAEAHAKQAGALAKAJQAKAKALAHQALAIAGgBIAHAAQAIAAAIgEQAIgFAHgHQAHgHAFgJQAEgJAAgLIgCgfQAAgHgCgEIgFgJIgRgXIgOgLIgIgEIgIgCIgLAAIgSgCQgGAAgFAJg");
	this.shape_1.setTransform(-36.2,1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.3,-7.9,0.3,7.8).s().p("AgqBlIgOgDIgJgFQgIgDgCgHQgBgHADgGQAAgEADgCIAHgGQAFgFAGAAQAGAAAEAEIALAJIAFAHIAHAIIAIADIALABIAIgBIAMgEQAGgDADgHQAEgHAAgIIgCgPIgEgMQgCgFgFgFQgEgEgIgCIgBgBIgCgBIgNADQgIAEgHABQgHAAgFgCQgGgCgEgEQgDgEgBgFQAAgCADgFQAEgGAIgDIAGAAQAEAAAGABQAHABAHgBQAFAAAGgFQAHgFAGgKIAEgIIACgKIgHgRIgHgIQgEgDgGAAIgFABIgHgBIgJADIgQANIgJAJIgJAOIgCAEIgJADQgFAAgDgEIgEgDIgBgFIACgSIgCgOIABgMQACgHAEgDQAEgEAKACQADABADACQACACADAAIACABIABABIArgJIAXABQAHAAAFADIAMAGIAJAIIAGAJQAEAIAAAIQABAIgDAJIgGAOIgKAOIgIAEIgRAFQgBAAgBAAQAAAAAAAAQAAAAAAAAQAAABABAAIABABIACABIATAEIAIABIAJAHIALALQAFAGAAAGQABAJgBANQgDALgGAJQgGAJgKAHIgTAKQgHAEgJABIgSABg");
	this.shape_2.setTransform(-54.8,2.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.3,-10.1,0.5,10.1).s().p("Ag8BWQgKgGgGgLIgQglQgGgSgCgQIACgNIAFgOIABgLIAHgQIAIgNIAJgMQAFgFAEgBIAJgDIAJgBIAPgHIAHgBIAWgBIAMACIAIAAIAQAGIADACIANAEQAIACAEAEIAMARQANAKAEAJQADAJABAIIABAfIgDAMIgSArQgDAHgFAFIgfAXQgHAGgLAAIgWAAIgDAAIgTABgAglg+QgGAIgEAKIgHAVIgDANIABAaQAAAEAIAKQAGAKAKALQAJAJALAHQAMAIAGgBIAHAAQAHAAAJgEQAIgFAHgGQAHgIAFgIQAFgKgBgLIgCgfQAAgHgBgEIgGgJIgSgXIgNgKIgIgFIgIgDIgMABIgRgCQgGAAgGAJg");
	this.shape_3.setTransform(52.6,-2.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.2,-11.3,0.7,11.5).s().p("AhDBtIgBgCIgBgCIAHgQIAFgGIAlgMQADAAACgEIABgGIgBgyIADgIIgCgsIAAgLIgBgDIgDgDIgEgEIgFgCIgoABQgHABgEADQgEADgCAEIgFARIgEAIQgDACgGAAQgFABgDgEQgCgEAAgFIAAgKIAHgpIADgHQAAgBABgBQAAAAAAgBQABAAAAAAQABgBABAAQAEAAAEACIAKAGIAGABIANgCIAHAAIAGABIA4gCIAJgCIAKACIAwgFIALgCIAJgEIAJgFIACACIADAGIADAMIABAZIAAAGIAAAHIgEAIQgCAEgDAAQgGAAgDgDIgEgGIgFgRIgGgHQgEgCgIABIgXAAIgIADQgIABgEAFQgDAEAAAHIABAWIABAEIACBGIABALIADAIIAIAIIALAEIAKABQALABAFAFQAFAEABAFQABAGgEAEQgEAFgJABIgMgCIgXAAIgGgCIggABIgJACQgHACgIAAIgYAAIgDABQgBACgGABIgBgCg");
	this.shape_4.setTransform(30.4,-1.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.3,-10.1,0.5,10.1).s().p("AgVBlIgJgDIgegNQgKgEgHgMIgPglQgGgTgBgQIABgMIAFgPIACgKIAHgRIAQgYQAFgFAEAAIAJgEIAJgCIAPgGIAHgBIAWgBIANACIAIAAIAfAMQAHACAGAEIALARQAOAKADAIQAEAKAAAIIAAAfIgCAMIgSArQgCAHgGAFIgeAXQgHAHgLAAIgYgBIgCABgAgkg+QgGAIgEAKIgIAVIgCAMIABAaQAAAFAHALQAGAKAKAJQAKAKALAHQAKAIAIAAIAGgBQAIAAAHgEQAJgFAHgGQAIgIAEgJQAFgKAAgKIgCgfQAAgIgDgEIgEgIIgSgWIgOgMIgIgEIgIgCIgMAAIgRgCQgGAAgFAJg");
	this.shape_5.setTransform(7.8,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.6,-12.7,125.4,25.4);


(lib.Символ67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.5,-13,0.5,13).s().p("AgoB/IgmgQQgNgHgJgPIgUgvQgIgZgBgVIACgQIAGgSIACgOIAJgVIAJgRIANgPQAGgHAFAAIAMgFIALgCIAUgHIAIgCIAdgCIARAEIAKgBIAUAHIAFADIAQAFQAJADAGAGIAQAVQARANAFAMQAEAMABAKIABApIgEAPIgXA3QgDAKgIAGIgmAdQgKAJgOAAIgegBIgDABIgZABgAgwhQQgHAKgGAOIgJAbIgEAPIACAjQAAAFAJANQAIAOANAMQANANANAJQAOAKAJgBIAJAAQAKgBALgEQAKgGAKgKQAJgJAGgLQAGgMgBgOIgBgpQgBgJgCgGIgegoIgSgOIgKgGIgKgDIgPABIgXgDQgIAAgHAMg");
	this.shape.setTransform(49.7,-2.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.4,-10.2,0.3,10.1).s().p("Ag3CEIgRgGIgMgFQgKgFgCgIQgDgJAFgIQAAgEAEgFIAIgFQAGgIAIAAQAIAAAGAGIAOALIAGAKIAKAJIAKAEIANACIALgCIAQgEQAHgFAFgKQAFgIAAgLIgCgSIgFgQQgEgIgGgFQgGgFgJgDIgCgBQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgQADQgKAGgKAAQgIABgIgCQgHgCgFgGQgEgFgBgGQgBgFAEgGQAFgGALgFIAHABQAFgCAIACQAJACAJgCQAGAAAKgHQAIgGAIgMIAFgLIADgOIgJgVIgJgLQgFgDgJAAIgGAAIgJgBIgMAFIgVAQIgLALIgMAUIgDAFIgLACQgHACgDgFIgFgEIgCgIIADgYIgDgQQAAgJACgJQACgIAFgDQAGgFAMACQAEABAEADQACADAEgBQAAABABAAQAAAAAAABQAAAAABAAQAAAAABAAIACABIA3gMIAeABQAJAAAHAFIAPAIIALALIAHAKQAGALABALQAAALgEAKIgIAUIgMAQIgKAFIgWAHQgEAAADACIAAABIADAAIAZAFIALADIALAJIAOAOQAGAIAAAIQACAMgCAQQgDAQgIAKQgJAMgMAIIgYAPQgKADgLABIgpABg");
	this.shape_1.setTransform(25.7,-1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.5,-14.4,0.6,14.5).s().p("AgwCHIgJgDIgVgDIgEACIgFACIgdABQgGAAgHgCQgHgEAAgHIABgMQACgGAHAAIAIgDQAEAAAEgFQAFgGAAgCIgBgfIgHgfIgBgZIADgIIACgNIgGgVIAEgRIgBgfQAAgDgGgBIgYgFIgGgCQAAgJAFgGQAGgHAFAAIAfgDIAKACQAFADAHAAIANgFIAbgBQAFAAACAFIAAAEQABAKgCAEQgDADgEACIgTAEQgEADgCAEQgDAGAAALIAFAXIABAOQAAAIAGAHQAGAHAKAAIAGgCIADgCIARADIAagBQAIAAADAEIAEgBIADgBIAEgDIACAAIASgBIAFgHIACgHIgBgkIgGgWIgBgIQAAgFgDgBIgOgHQgDgCgBgIQAAgFAGgFQAEgFAHAAIANADIAaADIASgBIAWAFIAIAGQAEAEAAAHIgCAGIgKACIgNAAQgDAAgEAHQgGAGABAFIABAxIAEAUIgGAQIAFAzIgCAYIABAMQACAFAGADIAdALQAGADAAADIgCAFIgEAEIgGAFIg0ACIgVgFIgNAGIgEAAIgGgBIgFgCIgCgGQAAgEAFgEIASgTQAFgGAAgLIgCg0IgDgJQgDgEgEAAIgdABIgSgEIgqABQgJABgHAEQgFAEAAALIABAdIgDANIADAIIACAJQgDAHAFAEIAKAIIANAHQAHAEAAAFIgCADIgFACIgJADg");
	this.shape_2.setTransform(-0.1,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.5,-13,0.5,13).s().p("AgoB/IgmgQQgNgHgIgPIgVgvQgHgZgCgVIADgQIAFgSIADgOIAIgVIAKgRIAMgQQAGgGAFgBIAMgEIAMgCIATgHIAIgDIAdgBIARAEIAJAAIAUAFIAFAEIARAFQAJADAGAFIAPAWQARANAGALQAEAMAAALIABApIgDAPIgYA3QgCAKgIAGIgmAdQgLAJgNAAIg6AAgAgxhQQgGAKgGANIgJAbIgDAQIABAiQAAAGAJANQAJANALANQAOANANAJQAOAKAJgBIAJAAQAJgBALgFQALgGAJgJQAJgJAHgLQAFgMAAgOIgCgpQAAgKgDgEIgdgpIgcgUIgKgDIgPABIgXgEQgIAAgIANg");
	this.shape_3.setTransform(-29.8,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FFCE00","#FFEEAD","#B99400"],[0.051,0.702,1],-0.2,-9.9,0.5,9.6).s().p("AhOCCIgGgDIgFgGIgBgIQAAgKAFgDIAUgOQAEgFABgNIAAgFIADgGIABgHIgFh4QABgOgGgDQgFgEgHgCIgMgDQgGgCABgKIAAgFIABgHIAEgFQADgCAFAAIAFACIANACIAegGIAWAEIAHAAIACABIACgBIACgBIBFgBIAJABIAHAPIAKA3QAAACgEADIgIAEQgIAAgEgGQgDgGgJgFIgjgXIgZABQgCAAgCADIgIANIgBAFIAAAaIACAJIgEAgIAIA3IgDAOQAAAKAGAFQAEAGAJgBIAOAAIAEABIARAKIgCAKQAAAHgFADQgGAEgHAAIhiAEg");
	this.shape_4.setTransform(-53.1,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.7,-15.4,125.5,30.9);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Egg2AMFIAA4JMBBtAAAIAAYJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-210.3,-77.3,420.7,154.6);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.iii();
	this.instance.setTransform(-124,-13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124,-13,248,26);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AE8BbIgEgCIgEgFIgEgGIgBgEIAAgEIACgRIgBgsIABgJIABgsIgBgHQgCgEgCABIgFAAIgGgFIgEABIgEAAIgDgBIgFgDIgCgDIAAgFQAAgGAFgDQAFgCAGAAIAzABIAGgBIAPgBIAFABIADACIABAFIABABIABACIAAADIgBACIgIAFIgEABIgHADIgDACIgGAIIgDADIgCAZIACAiIgBAJIABAFQAAABAAAAQABABAAAAQAAAAABAAQAAABABAAQADgBAFgFIAdgiQAGgEADgFIAigoIAIgFQAEgDACgGIADgEIAFgFIAFgGQADgDADAAQAHAAACACQACADABAGIgCAbIgCAPIAAAKIAAAEQgCADAAADIAAAXIACAKIAAAGIAAAEIAAADIAAAMIgCAGIAAADIACADIACADIADACIASADIAFABQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABIAAAFIgBADQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgGgBIgLAAQgEAAgDACQgDABgGAAIgLAAQgDABgDACIgSgDIgfAAIgDAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgEADgDQADgCAFgBIAUgFQAFgBADgDQADgCAAgGIgBgPIADgQIAAgqQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAIgFACIgFAGIgEAFIgCAEIgXAZIgNANIgLAOIgQAaIgUATQAAACgEAAgAlsBTIgTgBIgFgCIgcAAIgHABQgFACgHAAIgTgBIgDABQgBABgEAAIgCgBIAAgBIgBgCIAGgMIAFgGIAegIQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIABgGIABgnIABgFIABgBIAAgkIABgJIgBgCIgCgEIgDgDIgEgBIghAAQgGAAgDACQgDACgCAEIgFAOIgDAGQgDABgEAAQgFAAgCgCQgBgEAAgEIAAgIIAFgXIABgEIABgGIADgGQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQAEAAACACIAIAFIAGABIAKgCIAGAAIACABIACABIAvAAIAIgCIAIACIAngCIAJgBIAIgDIAHgFIACADIACAFIACAKIAAAUIAAAFIgBAGIgCAGQgCADgDAAQgFAAgCgCIgDgFIgEgPIgEgGQgEgCgGAAIgTAAIgGACQgHAAgDAFQgDAEAAAFIAAASIABAEIgBAMIAAAsIABAKIACAFIAGAHIAIAEIAJABQAIABAFAEQAEAEAAAEQABAEgEAEQgDADgHACgAy2BVIgXgEIgKgDIgIgEQgGgDgBgGQgCgFAEgFQAAgDACgCIAGgEQAEgEAFAAQAFAAADAEIAJAHIADAHIAGAFIAHAEIAIABIAIAAIAKgEQAFgDADgFQADgFAAgHIAAgLIgDgKQgCgFgEgEQgDgEgGgCIgBAAIgCgBIgMABQgGAEgGAAQgGABgEgDQgFgBgDgDQgCgEgBgEQAAgCADgEQADgDAHgEIAEACQAEgCAFACQAFABAGAAQAFAAAGgFQAGgDAFgIIADgGIACgJIgFgNIgFgIQgDgCgGAAIgFAAIgGgBIgHADIgGADIgDAEIgFACIgHAIIgIALIgCADIgHACQgEAAgCgDIgDgDIgBgEIACgPIgBgLQAAgFABgGQACgFADgCQAEgCAHABQADABACACQABAAAAAAQAAABABAAQAAAAABAAQABAAAAAAIACABIABABIANgCIAMgCIALgBIATABQAGAAAEACIAJAGIAHAHIAFAHQADAHAAAHQAAAHgCAGIgGAMIgIAKIgHADIgOAEQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIABABIABABIAQABIAHADIAHAGIAIAJQAEAFAAAFQABAIgCAKQgDAJgFAHQgFAHgJAFIgPAIQgGADgHABgAOLBSQgDgCAAgCQAAgDAEgDIAOgKQADgDgBgEQgCgEABgDIABgEIAAhDIgDgIIADgOIgBgJIgCgGIgEgCIgHAAIgEgBQgCgBgBgEIgBgIIAAgCIABgCIABAAIARAAIACAAIAGACIAFAAIALgCIADAAIADgBIABgBIAMACIADAAIACABIADADIACAEIABAEQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIgQAEQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAAAIAAAVIACAHIABAEIgDANIAFAdIgBALIgBAIIAAAIIgCADQgBABAAAGIABADIACACIADADIAIADQAIADAAAIQAAAEgEACQgFADgFgBIgQAAIgLgDIgWAGgAC8BSQgDgCAAgCQAAgDAEgDIAOgKQADgDgBgEQgCgEABgDIABgEIAAhDIgDgIIADgOIgBgJIgCgGIgEgCIgHAAIgEgBQgCgBgBgEIgBgIIAAgCIABgCIABAAIARAAIACAAIAGACIAFAAIALgCIADAAIADgBIABgBIAMACIADAAIACABIADADIACAEIABAEQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIgQAEQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAAAIAAAVIACAHIABAEIgDANIAFAdIgBALIgBAIIAAAIIgCADQgBABAAAGIABADIACACIADADIAIADQAIADAAAIQAAAEgEACQgFADgFgBIgQAAIgLgDIgWAGgAIDBTIgDgBIgDgCIgDgDIgBgFQAAgHADgCIANgIQADgCABgJIAAgDIACgEIABgEIAAhLQABgIgEgDQgDgCgEgBIgIgDQgDgBABgHIAAgDIABgEIACgDQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADACIAIABIATgDIAOADIAEABIACABIABgBIADgBIAhAAIAQADIADAJIAGAjQAAAAAAAAQgBABAAAAQAAABgBAAQgBAAAAABIgFACQgFAAgDgEQgCgDgFgEIgSgOIgDgCIgQAAQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAAAIgDAFIgCADIgBAEIgBAPIABAGIgDAUIADAiIgCAJQAAAHAEADQADADAGABIAJAAIADABIAKAHIgCAFQAAAEgDACQgEADgEAAgAMkBSIgIgCIgCABIgFABIgGAAIAAgBIgBgBIgDAAIgDgBQgEAAgBgBIgCgEIACgJQABgDAEAAIAFAAIANgDIACgBIABgCIgBgFQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIAAgIIACgIIABgOIAAgBIAAgCIABg6QABgJgFgCQgEgDgGgBIgKgCQgFgCABgGIABgDIAEgEIAFgDIAGgCIADACIADAAIAUAAIAEAAIAOAAIAEAAQACACAFgCIAMAAIAHAAIAFACQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAFgCAFQgCAEgGAAIgQACQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAABIgFAEIgDAGIgBADIAAANIgBAEIAAADIAAAFIAAAKIABABIAUgBIAVACIAIADIAFACIAFABQADAAADAEIAEAGIADAIIACAIIgBAUQAAAFgEAGIgCAEIgCADIgCADIgEACQgJAGgMADQgLAEgMgBgAM/ALIgEAHIgCAIIAAAGIAAATIAAADIACADIADADIAEACIAIgBIAPgFIAJgEIAGgHQADgDgBgEIAAgQQAAgEgEgCIgHgFIgJgCIgRAAQgEAAgCACgALDBSIgOgDIgTAAIgbADIgGAAIgGgCIgDgCIgBgHIAAgFIABgFIADgFQACgBAEAAIADACIALAAQAIAAAAgIIAAgIIABgMIgBgFIABgHIAAgPIABgCQABAAAAgHIAAgQIgCgEQgBgCAAgFIAAgIIABgHIACgEQAAgEgEgDQgEgEgGABIgDAAIgDgBIgGgBIgFgDQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIABgFIADgEIAEgBIADgBIADAAIACACIAyAAIAYAFIAIAAQAJAAAFAGQAGAGADAIQAEAHABAIIACANIgBAKIgDAMQgCAFgEAEQgFAFgHACIgHADIgEACIgCAAIgGAAIgHgCIgHgEQgCgBAAgDQAAgFACgBIAOgCQAEgBAEgDQADgDADgHQACgGAAgMIAAgDIgCgFQgDgDgEgCIgJgFIgJgCIgFgBIgFAAIgDABIgCABIgCADIABADIAABCIADAOIgDAMIAAAEQAAAIAEADQAEACAFAAIAKAAQAEABAAAFIAAADIgBADIgCAEIgDADIgCABgABVBSIgIgCIgCABIgFABIgGAAIAAgBIgBgBIgDAAIgDgBQgEAAgBgBIgCgEIACgJQABgDAEAAIAFAAIANgDIACgBIABgCIgBgFQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIAAgIIACgIIABgOIAAgBIAAgCIABg6QABgJgFgCQgEgDgGgBIgKgCQgFgCABgGIABgDIAEgEIAFgDIAGgCIADACIADAAIAmAAIAEAAQACACAFgCIAMAAIAHAAIAFACQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAFgCAFQgCAEgGAAIgQACQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAABIgFAEIgDAGIgBADIAAANIgBAEIAAADIAAAFIAAAKIABABIAUgBIAVACIAIADIAFACIAFABQADAAADAEIAEAGIADAIIACAIIgBAUQAAAFgEAGIgCAEIgCADIgCADIgEACQgJAGgMADQgLAEgMgBgABwALIgEAHIgCAIIAAAGIAAATIAAADIACADIADADIAEACIAOgDIAJgDIAJgEIAGgHQADgDgBgEIAAgQQAAgEgEgCIgHgFIgJgCIgRAAQgEAAgCACgAg0BSIgIgCIgCABIgFABIgGAAIAAgBIgBgBIgDAAIgDgBQgEAAgBgBIgCgEIACgJQABgDAEAAIAFAAIANgDIACgBIABgCIgBgFQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIAAgIIACgHIABgNIADgPIAAgCIgBgBIAAAAIABgLIAAgJIACgLQAAgIgCgFQgDgEgEgEIgXgLQgDgCAAgEQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAFgEIAKgDIAGAAIAMgCIAXAAQAAAAABABQAAAAAAABQABAAABAAQAAAAABAAIAIAAIAQACQAGACAHAEQAGAEAGAGQAGAHAEAJIAAAPQAAAFgCAEIgLAOIgDAFIACADIACAAIAEADQADAAADADIAEAGIAEAJIABAHIgBAOIgBAJIgCAFIgDAEIgCADIgCADIgEADQgJAFgLAFQgIADgMAAgAgZAOIgEAGIgCAHIAAAYIAAADIACADIADADIAEACIAGgBIANgFIAGgFIAGgHQADgEgBgEIAAgJIAAgCIAAgBQAAgEgDgDIgHgEIgHgCIgNgBQgEAAgCAEgAgVg0IgFAGIgDAFIAAAFIAAASIADALIADADIAGABIAGgBIAHgEIAFgFQADgCAAgDIAAgQIgCgGIgEgGIgHgGQgEgBgEAAgAkOBSIgIgCIgDABIgEABIgGAAIAAgBIgCgBIgDAAIgCgBQgEAAgCgBIgBgEIABgJQACgDAEAAIAFAAIAMgDIADgBIABgCIgBgFQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIAAgIIACgJIAAgOIABgBIgBgDIABg4QABgJgEgCQgFgDgGgBIgKgCQgEgCABgGIABgDIADgEIAFgDIAGgCIADACIAEAAIAUAAIAEAAIANAAIAEAAQACACAEgCIAKAAIAHAAIAFACQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgCAFQgCAEgGAAIgQACQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBABIgDAEIgCAGIgBADIAAANIgBAEIAAADIABADIgBALIABAAIAUAAIAWACIAHACIAGADIAEABQADAAADADIAFAGIADAJIABAHIgBAWQAAAFgDAGIgDAEIgBADIgCADIgFACQgIAGgMADQgMAEgMgBgAj0AKIgDAHIgCAHIgBAFIAAAWIABADIACADIADADIAEACIAOgDIAIgDIAJgEIAHgHQACgDgBgEIAAgSQAAgDgDgDIgIgEIgJgCIgQAAQgEAAgDACgAqRBRIgGgCQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgEADgFQAEgEAFAAIAGAAIACgBIAKgIIAqhoIAEgUIAFgLIAJgIIAFAAQAFAAADADIAEAHIAEAJIADAUIAFAJQADAFAAAGIASBFIAHAQQADAFADABIADAAIABABIABAAIABABIACAAIAEAAIADADIABAFQAAAFgEADQgEACgFAAIgugBIgIABIgFAAQgBAAgBgBQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgFADgCIAQgIQAEgCAAgEIgBgEIgBgHIgDgGQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAAAIgDgMIgDgFQgCgBgEAAIgOAAIgIABIgDACQgEABAAAEIgBAHIgFALIgDAKQAAADACACIAEACIAEAEQACADAAAFIgBADIgDACIgDAAIgDAAIAAABIgCAAIgCgBIgEAAIgJgBIgSACIgCABIgBABIgBAAgApBgjIgFAIIgBAKIgCACIgBAGIAAAHQAAAAAAABQAAAAABABQAAAAABAAQAAAAABAAIAGAAIAHAAIAEAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgEgCgEIgCgHIAAgMIgBgGIgDgCQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBABAAAAgArYBSIgOgDIgTAAIgbADIgGAAIgGgCIgDgCIgBgHIAAgFIABgFIADgFQACgBAEAAIADACIALAAQAIAAAAgIIAAgIIABgMIgBgFIABgHIAAgPIABgCQABAAAAgHIAAgQIgCgEQgBgCAAgFIAAgIIABgHIACgEQAAgEgEgDQgEgEgGABIgDAAIgDgBIgGgBIgFgDQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIABgFIADgEIAEgBIADgBIADAAIACACIAyAAIAYAFIAIAAQAJAAAFAGQAGAGADAIQAEAHABAIIACANIgBAKIgDAMQgCAFgEAEQgFAFgHACIgHADIgEACIgCAAIgGAAIgHgCIgHgEQgCgBAAgDQAAgFACgBIAOgCQAEgBAEgDQADgDADgHQACgGAAgMIAAgDIgCgFQgDgDgEgCIgJgFIgJgCIgFgBIgFAAIgDABIgCABIgCADIABADIAABCIADAOIgDAMIAAAEQAAAIAEADQAEACAFAAIAKAAQAEABAAAFIAAADIgBADIgCAEIgDADIgCABgAuTBSIgIgCIgCABIgFABIgGAAIAAgBIgBgBIgDAAIgDgBQgEAAgBgBIgCgEIACgJQABgDAEAAIAFAAIANgDIACgBIABgCIgBgFQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIAAgIIACgHIABgNIAAgBIAAgCIABg8QABgJgFgCQgEgDgGgBIgKgCQgFgCABgGIABgDIAEgEIAFgDIAGgCIADACIADAAIAUAAIAEAAIAWACIACgBIAnABIAGACIACAIIAEAiQAAACgDADIgFACQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBIgDgGIgDgHQgCgEgDgBQgEgDgFgDIgHgCIgOAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABIgDAEIgDAGIAAADIAAAMIgBADIAAACIAAACIAAAOIABAAIAVAAIAWACIAHACIAGADIAFABQADAAACADIAFAGIADAJIABAHIAAANIgCAPIgCAFIgDAEIgBADIgCADIgEACQgKAGgLADQgMAEgMgBgAt4AKIgEAHIgCAHIAAAFIAAAWIAAADIACADIADADIAEACIAJgBIAQgFIAIgEIAHgHQACgDgBgEIAAgSQAAgDgDgDIgIgEIgJgCIgSAAQgEAAgCACgAxXBRIgHgCQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgEADgFQADgEAGAAIAFAAIACgBIAKgIIAqhoIAFgUIAEgLIAKgIIAFAAQAEAAADADIAFAHIADAJIAEAUIAEAJQADAFAAAGIATBFIAGAQQADAFAEABIACAAIACABIAAAAIABABIADAAIADAAIADADIACAFQAAAFgEADQgEACgGAAIgtgBIgIABIgGAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgFAEgCIAQgIQADgCAAgEIAAgEIgCgHIgCgGQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAIgDgMIgDgFQgCgBgDAAIgOAAIgJABIgDACQgDABgBAEIgBAHIgFALIgDAKQAAADACACIAEACIAFAEQABADAAAFIgBADIgCACIgEAAIgCAAIgBABIgBAAIgDgBIgDAAIgJgBIgSACIgDABIgBABIgBAAgAwIgjIgEAIIgCAKIgBACIgCAGIAAAHQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIAFAAIAHAAIAEAAQABAAAAAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgEgCgEIgCgHIAAgMIgCgGIgDgCQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAABgBAAgAPgBQQgDgBAAgEIAAgDIACgCIAGAAIANgLIACgDIABgDIABgDQABgJAAgEIgBgHIACgKIgBgOIAEgJIAAgnIAAgCIABgBIAAgDIgBgJQAAgCgFgDIgSgHQgFgCAAgCIACgEIACgCIAEgCIAhAAIAOACIAIgCIADAAIAEABIADABIACADQAAAEgEABIgGAFIgHAGQgDAFAAAHIAABnQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAEACIAoABQAGgBAGgCQAFgDAAgGIgBgiIABgEIAAg6IgBgFQgBgDACgEQABgEgDgCIgOgJQgDgCAAgDQAAgDADgBIAFgBIAVACIAIgBIAEACIAFgBIADgBIAPABIADABIABADQAAAEgDAEQgDAEgCAAIgFAEQgCABgCADQgCAEAAADIAABRIgBAHIAAAPQAAAEAFACQAFABAGABIApgBIADgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIAAhoQAAgHgDgEIgGgHIgHgEQgDgCAAgDIABgEIADgBIAEgBIADAAIAYACIAOgCIARAAIAEACIADACIABAEQAAACgEACIgRAIQgEABAAADIgBASIABAGIAAAFIgCAZIACAKIgBANIACAKIAAAHIACAQIABAEIACAEIACACIAKAGIAFAAIACADIABACQAAAFgDABIgGABIg4gBIgJABIgJAAIgGAAIiZAAIgQABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.6,-9.1,251.3,18.3);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.uuu();
	this.instance.setTransform(-122,-29);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122,-29,244,58);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.mmm();
	this.instance.setTransform(-78,-16.3,1.258,1.258);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78,-16.3,156,32.7);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fff();
	this.instance.setTransform(-328.7,-156.6,0.938,0.938);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-328.7,-156.6,657.4,313.3);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,216,0,0)","#FFD800","rgba(255,216,0,0)"],[0,0.51,1],-34.5,0,34.5,0).s().p("AlXSlMAAAglJIKvAAMAAAAlJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.5,-119,69,238);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.nnnn();
	this.instance.setTransform(-134.4,-136.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134.4,-136.4,269,273);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ooo();
	this.instance.setTransform(-116.7,-207.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.7,-207.4,367,373);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.sss, null, new cjs.Matrix2D(1,0,0,1,-44.5,-46)).s().p("Am7HMIAAuXIN3AAIAAOXg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.4,-46,89,92.1);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ddd();
	this.instance.setTransform(-44.5,-46.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.5,-46.5,89,93);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aas();
	this.instance.setTransform(-45,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45,-46,90,92);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.uuu();
	this.instance.setTransform(-179.1,-42.6,1.468,1.468);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-179.1,-42.6,358.2,85.2);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.asdgasdgasdfgsdg();
	this.instance.setTransform(-218.5,-88);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-218.5,-88,437,176);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ggg();
	this.instance.setTransform(-81.2,-83.1,0.961,0.961);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.2,-83.1,162.5,166.3);


(lib.Анимация4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.525,1],-32.9,-15.2,33,15.3).s().p("A0ASxMAVcguKISlIpMgVcAuKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.1,-175.4,256.4,350.9);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.525,1],-32.9,-15.2,33,15.3).s().p("A0ASxMAVcguKISlIpMgVcAuKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.2,-175.4,256.4,350.9);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.51,1],-33,0,33,0).s().p("AlJL8IAA34IKTAAIAAX4g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33,-76.5,66,153);


(lib.Анимация1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.51,1],-33,0,33,0).s().p("AlJL8IAA34IKSAAIAAX4g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33,-76.5,66,153);


(lib.Слой4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.rrr();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,57,77);


(lib.Слой3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.eee();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,33,59);


(lib.Слой2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.www();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,42,56);


(lib.Слой1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.qqq();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,114,168);


(lib.Символ66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_19 = new cjs.Graphics().p("ApWGoIgGgDIgFgFIgBgIQAAgKAFgEIAUgNQAEgFABgOIAAgEIADgGIABgIIgFh6QABgNgGgEQgFgEgHgBIgMgEQgGgCABgJIAAgGIABgGIAEgFQADgDAFAAIAFADIANABIAegGIAWAEIAHABIACABIACgCIAEAAIBFgBIAJABIAHAPIAKA2QAAACgEAEIgIADQgIAAgEgGQgDgFgJgFIgjgYIgZABQgEABgCADIgIANIgBAFIAAAZIACAJIgEAjIAIA2IgDAPQAAAJAGAGQAFAFAKAAIAOgBIAEACIARAKIgCAJQAAAHgFADQgGAEgHABIhkAEgAlGGWIgngQQgNgHgIgPIgUgwQgIgYgBgXIACgQIAGgSIACgOIAIgWIAKgQIAMgQQAGgGAFgBIAMgFIAMgBIATgIIAIgCIAfgBIARADIAKAAIAUAGIAFADIAQAGQAJACAGAGIAQAWQARANAFALQAEAMAAAKIACArIgEAQIgXA3QgDAJgIAHIgmAdQgKAIgOABIg8AAgAlPDEQgHALgGANIgJAbIgDAQIABAkQAAAGAJANQAJANAMANQANANANAJQAOAJALAAIAJgBQAKAAALgFQAKgGAKgJQAJgJAGgLQAGgNgBgNIgBgrQgBgKgCgFIgegoIgcgUIgKgDIgRAAIgXgDQgIAAgHAMgAglGSIgJgDIgVgDIgEADIgFABIgeACQgGAAgGgDQgHgDAAgHIABgMQABgGAHgBIAJgCQADgBAFgFQAEgFAAgCIgBgfIgGgfIgBgbIACgIIACgNIgGgVIAFgRIgCgfQAAgDgFgCIgZgEIgFgDQAAgJAFgGQAFgGAGgBIAegCIAKACQAGADAGgBIAOgEIAbgBQAFgBABAFIABAEQAAAKgCAEQgDAEgEACIgTAEQgEACgCAFQgDAFABAMIAFAXIAAANQAAAJAGAHQAHAHAJgBIAHgCIADgBIAQACIAbgBQAIAAADAEIAEAAIACgBIAEgDIADgBIARAAIAGgHIACgHIgBgkIgHgXIAAgIQAAgEgEgCIgOgHQgDgCAAgHQAAgGAFgEQAFgGAHAAIANAEIAZADIATgBIAVAEIAIAHQAEAEABAHIgCAFIgLACIgMABQgEAAgEAGQgFAGAAAFIACAxIAEAVIgGARIAEA0IgCAXIABANQACAEAHAEIAcALQAGACAAADIgBAGIgEAEIgHAEIgzACIgWgFIgNAGIgDABIgHgCIgFgCIgBgFQgBgFAFgEIATgSQAFgGgBgLIgCg1IgDgIQgCgEgEAAIgdABIgTgFIgpACQgKAAgGAFQgGAEABAKIABAdIgEAOIADAHIACAKQgDAHAFAEIALAIIANAHQAGAEABAEIgDAEIgEACIgKADgADUGHIgRgFIgNgGQgKgEgCgJQgDgJAGgIQgBgEAEgFIAJgFQAGgHAIAAQAIgBAGAGIANALIAGAKIAKAJIALAEIANACIANgBIAQgFQAHgFAEgJQAFgJAAgKIgCgTIgFgQQgEgHgFgGQgGgFgKgDIgBgBQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgSADQgKAGgJAAQgJACgIgDQgHgCgEgGQgFgFgBgGQAAgHAEgFQAEgHALgFIAHABQAGgCAIACQAJACAIgBQAJgBAKgHQAIgGAHgMIAGgKIACgPIgJgVIgJgLQgFgDgIAAIgJAAIgJgBIgMAFIgVAQIgKAMIgMATIgDAFIgMADQgGABgDgFIgGgEIgBgHIADgZIgDgQQgBgJACgIQADgIAFgEQAGgFALACQAFABADADQADADAEAAQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIADABIA4gLIAeAAQAJABAIAEIAOAIIALALIAIAKQAGALAAALQABALgEAKIgJAUIgLAQIgKAGIgWAGQgEAAACACIABACIACAAIAZAFIALAEIAMAJIAOAPQAGAHAAAIQACAMgCAQQgEAQgHAKQgJAMgNAIIgYAPQgJAEgLABIgsABgAHTF3IgngQQgMgHgJgPIgUgwQgIgYgBgXIACgQIAGgSIACgOIAIgWIAKgQIAMgQQAHgHAEAAIAMgFIAMgBIATgIIAJgCIAfgBIARADIAJAAIAUAGIAFADIAQAGQAKACAGAGIAPAWQARANAFALQAFAMAAAKIABArIgDAPIgYA3QgCAKgIAHIgnAdQgKAIgNABIgegBIgGABIgZAAgAHKClQgHAKgFAOIgKAbIgDAQIABAkQAAAGAJANQAJANAMANQANANAOAJQAOAJALAAIAJgBQAJAAALgFQALgGAJgJQAJgJAGgLQAGgNAAgNIgCgrQAAgKgDgFIgegoIgSgPIgJgFIgKgEIgSABIgXgDQgHAAgIAMgApNBwIgOgEIgJgFQgIgDgCgHQgBgHADgGQAAgDADgDIAHgFQAFgFAGgBQAGAAAEAFIALAIIAFAIIAHAHIAIADIALACIAKgBIAMgFQAGgDADgHQAEgHAAgIIgCgOIgEgMQgCgGgFgFQgEgEgIgCIgBgBIgCgBIgPADQgIAEgHABQgHAAgFgCQgGgBgEgFQgDgDgBgFQAAgFADgFQAEgDAIgEIAGABQAEgBAGABQAHACAHgBQAHgBAGgFQAHgFAGgJIAEgIIACgLIgHgQIgHgJQgEgDgGAAIgHABIgHgBIgJAEIgQAMIgJAJIgJAPIgCADIgJADQgFABgDgFIgEgCIgBgGIACgSIgCgNIABgNQACgHAEgDQAEgDAKABQADABADACQACACADAAIACABIABABIAtgJIAXABQAHAAAFADIAMAHIAJAIIAGAIQAEAIAAAJQABAHgDAJIgGAPIgKANIgIAEIgRADQgBAAAAAAQgBAAAAAAQAAAAAAABQAAAAABAAIABACIACAAIATAEIAIADIAJAHIALALQAFAGAAAHQABAJgBAMQgDAMgGAIQgGAKgKAGIgTALQgHADgJABIgSABgAjsBkQgGgFgCgGQgBgNAGgJQAGgIALgDIAEgBIAFACIADACIAGACIAUgIIAEgFIAIgcIACgOIAAgcIgBgIIABgSIADgHIgDgIIAAgQQAAAAAAgBQgBAAAAgBQgBAAgBAAQAAAAgBAAIgTgCQgEgBgBgDQAAgHAEgFQAFgGAFgBIAPgDIAJAAIAQADIAHgBIBSgBIAJABIAHAEQADADAAAFIAAADIgCADIgUAGIgEAIIAAADQgCAKABAFIACAIIgCANIADASIgDAMIACA9QgBAEACAFQAAAEAFADIAWAHQAEADAAACIAAAEIgEAEIgFACIgpACIgQgDIgLAEIgDAAIgJgDIgCgEQAAgEAEgCIARgPQADgEAAgJIgFiCIgCgGQgCgEgDAAIgWACQgGADgDADIgBANIACAYIgDA2IgIAYIgEAKIgFAHQAAAFgDAEIgMANQgFAEgCAFQgDAFgFABQgEAAgBADIgFADIgGADIgSAEQgHAAgHgFgAlmBlIgFABIgTAAIgngQQgKgFgGgLIgQglQgGgTgBgQIABgMIAFgOIACgLIAGgQIAIgNIAJgMQAFgFAEAAIAJgEIAJgCIAPgGIAHgBIAYgBIANADIAHgBIAPAFIAFADIAMAEQAHACAFAEIAMARQANAKAEAJQADAJABAIIAAAfIgCAMIgSAqQgDAIgFAFIgeAXQgHAGgLABgAmNg9QgGAIgEAKIgKAiIABAaQAAAEAHAKQAGALAKAJQAKAKALAHQALAIAIgBIAHAAQAIAAAIgEQAIgFAHgHQAHgHAFgJQAEgJAAgLIgCgfQAAgHgCgEIgFgJIgRgXIgOgLIgIgEIgIgCIgNAAIgSgCQgGAAgFAJgAA3BVIgJgDIgegNQgKgFgGgLIgOglQgGgRgBgSIABgMIAFgPIACgKIAHgRIAOgYQAFgFAEgBIAJgDIAJgCIAPgGIAHgBIAYgBIANACIAIAAIAfAMQAIACAFAEIAMARQANAKADAIQAEAKAAAIIABAhIgDAKIgRAqQgDAIgGAFIgeAXQgHAGgLAAIgXAAIgFABgAAohOQgGAIgEAKIgHAVIgDAMIABAbQAAAEAHAKQAGAKAKAKQAKAKALAHQALAHAJAAIAGAAQAIAAAIgEQAIgFAHgHQAIgHAEgJQAFgKAAgKIgCgfQAAgIgCgEIgFgIIgSgXIgOgLIgIgEIgIgDIgNABIgSgCQgGAAgFAJgADrBSIAAgCIgBgCIAGgQIAGgGIAlgMQACAAACgEIACgHIgCgvIADgIIgCguIABgLIgBgDIgDgEIgEgDIgFgCIgoABQgIABgEADQgDADgDAEIgEARIgFAIQgDACgFAAQgGABgCgEQgCgEgBgFIAAgLIAIgoIADgHQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAQAFAAADACIAKAGIAHABIAMgCIAIgBIAFACIA6gCIAKgCIAJABIAwgEIALgCIAKgEIAIgGIADADIADAGIADAMIABAZIgBAGIAAAHIgDAIQgCADgEAAQgGAAgCgCIgFgGIgEgSIgGgGQgFgCgHAAIgXABIgIADQgIAAgEAFQgEAFAAAHIABAVIACAFIABBGIACALIADAIIAIAIIAKAEIALAAQAKACAGAFQAFAEABAFQAAAGgEAEQgEAFgJABIgMgDIgXAAIgGgCIgiABIgIACQgHADgIAAIgYAAIgDABQgBACgGAAIgCgBgAHRA0QgKgFgHgMIgQgjQgGgSgBgSIACgNIAFgOIABgLIAHgQIAHgNIAKgMQAFgFADAAIAKgEIAIgBIAQgGIAHgCIAYgBIAMADIAIAAIAPAFIAEACIANAEQAHACAFAEIAMARQANAKAEAJQADAJABAIIAAAhIgCAMIgSApQgDAHgFAFIgfAXQgHAHgLAAIgXgBIgEABIgTAAgAHohgQgGAIgEALIgHAUIgDANIABAcQAAAEAHALQAHAIAJAKQAKAJALAHQALAIAJAAIAHgBQAHAAAIgEQAJgFAHgGQAHgIAEgIQAFgJAAgKIgCghQAAgHgCgEIgFgJIgSgWIgOgLIgHgFIgIgCIgOAAIgRgCQgGAAgGAJgAppiTIgCgBIgDgBIgCAAQgEAAgCgBIgBgEIABgIQABgEAEgBIAFAAIANgDIACgBIABgCIgBgFQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIgBgCIgBgHIACgIIAAgNIADgPIgBgCIgBAAIAAgDIABgLIAAgKIABgKQAAgIgDgFIgGgHIgYgLQgDgCAAgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAIAFgEIAKgDIAGAAIAMgDIAXgBIAEACIAYABQAIACAHADQAHAEAGAGQAGAGAFAJIAAAPQABAFgDAFIgKAOIgCAFIABADIAHAFQADAAACADIAFAGIAEAIIACAQIgCAOIgCAGIgCADIgCAEIgCADIgEACQgIAHgLAEQgLAEgMABIglABIgIgBIgDABIgEABIgGAAIAAgBgAo8jZIgEAHIgBAIIAAAXIABADIACADIADADIAEABIAGgBIAMgFIAJgGIAFgHQADgDgBgEIgBgKIABgCIgBgBQAAgEgDgDIgHgDIgJgCIgNAAQgEAAgCADgAo2keIgFACIgEAFIgDAGIAAAFIAAASIAEALIAEADIAGABIAFgCIAHgEIAHgFQADgDgBgCIAAgQIgCgGIgGgGIgIgFIgGgCIgBAAgAneiXIAAgCIgCAAIgDgBIgCAAQgEAAgCgCIgBgDIABgJQABgEAEAAIAFAAIANgDIACgBIABgCIgBgFQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIgBgBIgBgIIACgIIAAgOIAAgBIAAgCIgCg9QABgIgFgCQgEgDgGgBIgKgCQgFgBABgGIABgDIADgEIAFgEIAGgCIAHACIAUgBIADgBIAOAAIAEABQACABAGgCIALgBIAIABIAEACQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgBAKQgCAEgGABIgQACQgCABgCACIgEAEIgEAGIAAADIgBAVIABAEIAAALIABAAIAUgBIAVABIAOAEIAEAEQADAAADACIAFAHIAFAPIAAAVQAAAFgDAGIgEAHIgCADIgEACQgIAGgMAEQgMAEgMAAIgoACIgIgCIgHADgAmxjgIgEAHIgCANIABAUIABACIACAEIADACIAEACIAIgCIAOgEIAJgFIAGgHQADgDgBgEIgBgQQAAgEgEgDIgHgDIgJgCIgRAAQgEAAgCADgAjjiZIgEgBIgEgFIgEgGIgBgEIAAgFIABgQIgDgsIABgLIgBgsIgBgHQgCgEgCABIgFAAIgGgEIgFABIgDAAIgIgDIgCgEIgBgFQAAgGAFgDQAEgCAGAAIBJgEIAEABIAEACIABAEIABABIABACIAAADIgBACIgIAGIgEABIgHADIgCACIgGAIIgDAEIgBAYIADAkIAAAKIABAFQAAAAAAABQABAAAAAAQAAABABAAQAAAAABAAQADAAAFgGIAbgmQAHgDACgGIAhgpIAIgGQAEgDABgFIADgEIAFgFIAFgGQACgEAEAAQAGAAACACQADADABAGIgDApIABALIAAAEQgCADABADIAAAYIADALIAAAFIAAAEIAAAEIAAAMIgBAGIAAADIACADIACADIAEACIASABIAEACQABAAAAABQABAAAAAAQAAABABABQAAAAAAABIAAAFIgBADQAAABAAAAQAAABgBAAQAAABgBAAQAAABgBAAIgGgBIgLAAIgHACQgDACgGAAIgLABIgGADIgSgCIgfABIgDAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFADgCQADgDAFgBIAUgFQAFgCADgDQACgCAAgGIgBgOIABgRIgBgsQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAIgFACIgFAFIgFAJIgWAdIgNAOIgLAOIgPAaIgSAUQAAACgFAAgAliidQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgDADgDIAOgLQADgDgCgEQgCgFABgCIABgEIgDhFIgDgIIACgOIgBgJIgCgGIgEgBIgHgBIgEgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBgBgBIgBgIIAAgCIABgDIARgBIADABIAGACIAEgBIAKgDIADAAIADgBIABgBIAMACIAEAAIACABIADADIACAEIABAEQAAAAAAAAQAAAAAAABQgBAAAAAAQgBAAgBABIgPAEQgBABgBAAQAAAAgBABQAAAAgBABQAAAAAAAAIABAVIAEAKIgDAOIAHAeIgBALIgBAIIAAAIIgBADQgCABABAHIABACIACADIADACIAJADQAIADAAAIQAAAEgEACQgFADgFAAIgQAAIgLgDIgVAHgAgfipIgDgCIgDgDIgBgFQAAgGADgDIAMgIQADgDABgJIAAgDIABgDIABgFIgDhNQABgIgEgDQgDgCgFgBIgHgCQgEgCABgGIAAgDIABgEIACgDQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIADACIAIABIATgEIAQADIACAAIABAAIADgBIAhgBIAQABIAEAJIAGAjQAAAAAAABQAAAAAAAAQAAABgBAAQgBABAAAAIgFADQgFAAgDgEQgCgEgFgDIgTgNIgDgCIgQABQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAIgDAEIgDAIIAAAQIACAFIgDAWIAFAiIgCAKQAAAGAEADQADADAHAAIAIAAIADABIALAGIgCAGQAAAEgDACQgEADgEAAIg9ADgABgiuIgGgCIgDgCIgCgHIAAgFIABgFIADgEQACgCAEAAIADACIALgBQAIAAAAgIIgBgJIABgLIgBgFIABgIIgBgOIABgDQABgBgBgHIAAgQIgCgEQgBgCgBgFIAAgIIABgHIACgEQgBgEgDgDQgEgDgGAAIgHAAIgLgEQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBIABgFIADgEIADgCIAEgBIACABIADACIAygCIAYAEIAIgBQAJAAAFAGQAGAFAEAIQAEAIACAHIACANIgBALIgCAMQgCAGgEAEQgEAGgHACIgIADIgDACIgDAAIgGAAIgHgBIgGgDQgDgCAAgDQAAgEACgCIAOgEQAEgBADgEQAEgDACgGQACgHAAgLIgBgEIgCgEIgHgGIgJgEIgPgDIgFAAIgCABIgCACIgCADIABADIACBEIAEANIgDANIABAEQAAAIAEACQAFACAFAAIAJAAQAEABAAAEIAAAHIgCADIgDAEIgCABIgFABIgOgDIgTAAIgbAFgAG4i1IgEgFIgEgFIgBgEIAAgFIABgQIgDgsIABgLIgBgsIgBgHQgCgEgCAAIgFAAIgGgDIgFAAIgDAAIgDAAIgFgDIgCgEIgBgEQAAgGAFgDQAEgDAGAAIBJgEIAEABIAEADIABAEIABABIABACIAAADIgBACIgIAFIgLAFIgCACIgGAIIgDADIgBAZIADAkIAAAJIABAFQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQADAAAFgHIAbglQAHgEACgFIAhgpIAIgGQAEgDABgGIADgEIAFgEIAFgHQACgDAEAAQAGgBACADQADADABAFIgCAiIgBAIIABAKIAAAFQgCACABADIAAAZIADALIAAAFIAAAEIAAADIAAAMIgBAHIAAACIACAEIACADIAEABIASACIAEABQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAAFIgBAEQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAIgGAAIgLAAQgEAAgDACQgDACgGAAIgLABQgDAAgDACIgSgBIgfABIgDgBQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgEADgDQADgCAFgBIAUgFQAFgCADgDQACgDAAgFIgBgPIABgQIgBgsQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIgFADIgFAFIgFAJIgWAdIgNANIgLAOIgPAaIgSAUQAAACgFABIgHAAgADpi1IgGgBQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgFADgEQADgEAGAAIAFgBIACgCIAKgIIAmhrIADgVIAEgLIAKgIIAFAAQAEAAADADIAFAHIADAJIAFAUIAFAIQADAGAAAFIAcBWQAEAFADAAIADABIABAAIABABIABAAIACAAIAEABIADADIABAEQABAFgEADQgEACgGABIgtAAIgIACIgFgBQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgFADgCIAPgJQAEgBgBgFIAAgEIgCgGIgDgHQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgEgNIgDgEQgCgCgDABIgOABIgIABIgDACQgEACAAADIgBAHIgFALIgCAKQAAAEACABIAEADIAFAEQABABABAGIgBADIgDACIgDAAIgDAAIAAABIgCABIgCgBIgNgBIgSADIgCABIgBABIgBAAgAE0kuIgEAIIgBAKIgDAJIABAHQAAAAAAABQAAAAABABQAAAAABAAQAAABABAAIANABIADgCQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBIgDgIIgBgGIgBgNIgCgEIgDgDQAAAAgBAAQgBAAAAAAQAAAAgBABQAAAAgBAAgAHvl4IgFAAIgEgCIgEgDIgFgBIgEgDIgEgEIgCgGIgEgFIgCgGQAAgIAFgEQAFgEAIAAIAIABQAEAAAAAEIAAACIgBACIABACIABADIgBABIAAABIACAHIAFAFIAIADIAHABIANAAIAHgDQADgBADgDIAEgHIAEgPIgBgCIABAAQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADAAIAEACIADAHIgBACIgBAGIgBADIgBADIgCAEIgCADIgCADIgDAEIgDADIgTAJIgUADg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(19).to({graphics:mask_graphics_19,x:0,y:0}).wait(59));

	// Слой 2
	this.instance = new lib.Анимация3("synched",0);
	this.instance.setTransform(-138.5,-55.2);
	this.instance._off = true;

	this.instance_1 = new lib.Анимация4("synched",0);
	this.instance_1.setTransform(160.4,41.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.525,1],-32.9,-15.2,33,15.3).s().p("A0ASxMAVcguKISlIpMgVcAuKg");
	this.shape.setTransform(-138.6,-55.2);

	this.instance.mask = this.instance_1.mask = this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},19).to({state:[{t:this.instance_1}]},40).to({state:[{t:this.shape}]},18).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).to({_off:true,x:160.4,y:41.4},40).wait(19));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 69
	this.instance = new lib.Символ69();
	this.instance.setTransform(-356.4,-23.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7).to({x:15.2,y:-34.4},7).to({x:-0.8,y:-28.6},3).wait(43).to({x:-22.3,y:-25.4},3).to({x:238.8,y:-33.8},7).wait(7).to({x:-356.4,y:-23.1},0).wait(1));

	// Символ 68
	this.instance_1 = new lib.Символ68();
	this.instance_1.setTransform(-355.5,4.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({x:16.1,y:-6.9},7).to({x:0.1,y:-1.1},3).wait(49).to({x:-24.1,y:2.2},3).to({x:236.5,y:-26.3},7).wait(4).to({x:-355.5,y:4.4},0).wait(1));

	// Символ 67
	this.instance_2 = new lib.Символ67();
	this.instance_2.setTransform(-354.4,32.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({x:17.1,y:21.3},7).to({x:1.1,y:27.1},3).wait(55).to({x:-11.5,y:21.3},3).to({x:356.2,y:21.6},7).wait(1).to({x:-354.4,y:32.6},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-419.4,-37,127.8,85.1);


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ66();
	this.instance.setTransform(-0.1,-25.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ65();
	this.instance_1.setTransform(-0.1,-25.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-419.5,-62.9,127.8,85.1);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.setTransform(0.3,0);
	this.instance.compositeOperation = "lighter";
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ54();
	this.instance_1.setTransform(0.6,-1.4,0.907,0.902,0,0,0,0.5,-1.2);

	this.instance_2 = new lib.Символ52();
	this.instance_2.setTransform(0,0,1.424,1.424);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2,p:{scaleX:1.424,scaleY:1.424}},{t:this.instance_1,p:{scaleX:0.907,scaleY:0.902}}]}).to({state:[{t:this.instance_2,p:{scaleX:1.47,scaleY:1.47}},{t:this.instance_1,p:{scaleX:0.936,scaleY:0.932}}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-173.7,-41.3,347.4,82.6);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ57();
	this.instance.setTransform(3.6,17.7);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175.8,-25,358.8,85.3);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Слой1();
	this.instance.setTransform(0,0,1,1,0,0,0,57,84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57,-84,114,168);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Слой4();
	this.instance.setTransform(0,0,1,1,0,0,0,28.5,38.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.5,-38.5,57,77);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Слой3();
	this.instance.setTransform(0,0,1,1,0,0,0,16.5,29.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.5,-29.5,33,59);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Слой2();
	this.instance.setTransform(0,0,1,1,0,0,0,21,28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21,-28,42,56);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ33();
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.609},7).to({alpha:1},8).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.5,-119,69,238);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_30 = function() {
		this.gotoAndPlay(123);
	}
	this.frame_170 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_234 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(30).call(this.frame_30).wait(140).call(this.frame_170).wait(64).call(this.frame_234).wait(17));

	// Слой 17
	this.instance = new lib.Символ53();
	this.instance.setTransform(-2.3,498.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(52).to({_off:false},0).to({y:368.4},7).to({y:386.1},3).wait(44).to({y:368.4},3).to({y:498.1},7).to({_off:true},55).wait(52).to({_off:false},0).to({y:368.4},7).to({y:386.1},3).wait(1).to({y:368.4},3).to({y:498.1},7).wait(7));

	// Символ 26
	this.instance_1 = new lib.Символ26();
	this.instance_1.setTransform(-52.3,297.7,0.801,0.801);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(251));

	// Слой 15 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");
	var mask_graphics_30 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");
	var mask_graphics_122 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");
	var mask_graphics_171 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");
	var mask_graphics_201 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");
	var mask_graphics_250 = new cjs.Graphics().p("AutOuQmFmHAAonQAAonGFmFQGHmHImAAQInAAGGGHQGHGFAAInQAAInmHGHQmGGFonAAQomAAmHmFg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-1.2,y:273.9}).wait(30).to({graphics:mask_graphics_30,x:-1.2,y:273.9}).wait(92).to({graphics:mask_graphics_122,x:-1.2,y:273.9}).wait(49).to({graphics:mask_graphics_171,x:-1.2,y:273.9}).wait(30).to({graphics:mask_graphics_201,x:-1.2,y:273.9}).wait(49).to({graphics:mask_graphics_250,x:-1.2,y:273.9}).wait(1));

	// Слой 16
	this.instance_2 = new lib.Символ32();
	this.instance_2.setTransform(-1.4,268.3);
	this.instance_2.alpha = 0;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(48).to({alpha:1},4).wait(65).to({alpha:0},4).wait(21).to({y:551.4},6).wait(23).to({y:268.3},0).wait(48).to({alpha:1},4).wait(22).to({alpha:0},4).wait(2));

	// Символ 22
	this.instance_3 = new lib.Символ22();
	this.instance_3.setTransform(-2.1,-158.5);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({y:192.4},6).to({y:172.4},3).to({y:192.4},3).wait(21).to({scaleX:1.17,scaleY:1.17,x:-1.9,y:178.7},4).wait(65).to({scaleX:1,scaleY:1,x:-2.1,y:192.4},4).wait(19).to({rotation:15,y:475.5},6).wait(25).to({rotation:0,y:-158.5},0).wait(15).to({y:192.4},6).to({y:172.4},3).to({y:192.4},3).wait(21).to({scaleX:1.17,scaleY:1.17,x:-1.9,y:178.7},4).wait(22).to({scaleX:1,scaleY:1,x:-2.1,y:192.4},4).wait(2));

	// Символ 22
	this.instance_4 = new lib.Символ22();
	this.instance_4.setTransform(-4.2,-77);

	this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5).to({y:273.9},6).to({rotation:-19.2,y:263.9},3).to({rotation:0,y:273.9},3).wait(31).to({scaleX:1.17,scaleY:1.17,x:-4.3},4).wait(65).to({scaleX:1,scaleY:1,x:-4.2},4).wait(17).to({rotation:-30,y:557},6).wait(27).to({rotation:0,y:-77},0).wait(5).to({y:273.9},6).to({rotation:-19.2,y:263.9},3).to({rotation:0,y:273.9},3).wait(31).to({scaleX:1.17,scaleY:1.17,x:-4.3},4).wait(22).to({scaleX:1,scaleY:1,x:-4.2},4).wait(2));

	// Символ 22
	this.instance_5 = new lib.Символ22();
	this.instance_5.setTransform(-4.2,4.5);

	this.instance_5.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(3).to({y:355.4},6).to({rotation:6.2,y:350.4},3).to({rotation:0,y:355.4},3).wait(33).to({scaleX:1.17,scaleY:1.17,x:-4.3,y:369.1},4).wait(65).to({scaleX:1,scaleY:1,x:-4.2,y:355.4},4).wait(15).to({rotation:30,y:638.5},6).wait(29).to({rotation:0,y:4.5},0).wait(3).to({y:355.4},6).to({rotation:6.2,y:350.4},3).to({rotation:0,y:355.4},3).wait(33).to({scaleX:1.17,scaleY:1.17,x:-4.3,y:369.1},4).wait(22).to({scaleX:1,scaleY:1,x:-4.2,y:355.4},4).wait(2));

	// Символ 24
	this.instance_6 = new lib.Символ24();
	this.instance_6.setTransform(79.8,-166);

	this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(17).to({y:185},6).to({rotation:-9.2,y:175},3).to({rotation:0,y:185},3).wait(105).to({rotation:30,y:468},6).wait(31).to({rotation:0,y:-166},0).wait(17).to({y:185},6).to({rotation:-9.2,y:175},3).to({rotation:0,y:185},3).wait(51));

	// Символ 21
	this.instance_7 = new lib.Символ21();
	this.instance_7.setTransform(-75.2,-168);

	this.instance_7.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(13).to({y:183},6).to({rotation:15,y:173},3).to({rotation:0,y:183},3).wait(107).to({rotation:15,y:466},6).wait(33).to({rotation:0,y:-168},0).wait(13).to({y:183},6).to({rotation:15,y:173},3).to({rotation:0,y:183},3).wait(55));

	// Слой 6
	this.instance_8 = new lib.Символ24();
	this.instance_8.setTransform(-85.5,-83.1);

	this.instance_8.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(11).to({y:267.9},6).to({rotation:7.7,y:262.9},3).to({rotation:0,y:267.9},3).wait(106).to({rotation:-15,y:550.9},6).wait(36).to({rotation:0,y:-83.1},0).wait(11).to({y:267.9},6).to({rotation:7.7,y:262.9},3).to({rotation:0,y:267.9},3).wait(57));

	// Слой 5
	this.instance_9 = new lib.Символ21();
	this.instance_9.setTransform(85.3,-83);

	this.instance_9.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(9).to({y:267.9},6).to({rotation:-7.7,y:252.9},3).to({rotation:0,y:267.9},3).wait(106).to({rotation:60,y:551},6).wait(38).to({rotation:0,y:-83},0).wait(9).to({y:267.9},6).to({rotation:-7.7,y:252.9},3).to({rotation:0,y:267.9},3).wait(59));

	// Символ 24
	this.instance_10 = new lib.Символ24();
	this.instance_10.setTransform(77.8,-3);

	this.instance_10.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(7).to({y:348},6).to({rotation:9.2,y:343},3).to({rotation:0,y:348},3).wait(106).to({rotation:-30,y:631},6).wait(40).to({rotation:0,y:-3},0).wait(7).to({y:348},6).to({rotation:9.2,y:343},3).to({rotation:0,y:348},3).wait(61));

	// Символ 21
	this.instance_11 = new lib.Символ21();
	this.instance_11.setTransform(-77.2,-5);

	this.instance_11.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1).to({y:346},6).to({rotation:-8.7,y:339},3).to({rotation:0,y:346},3).wait(110).to({rotation:15,y:629},6).wait(42).to({rotation:0,y:-5},0).wait(1).to({y:346},6).to({rotation:-8.7,y:339},3).to({rotation:0,y:346},3).wait(67));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-145.8,131.6,293.9,298.7);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AtfNhQlnlnAAn6QAAn5FnlnQFmlmH5AAQH7AAFlFmQFnFnAAH5QAAH6lnFnQllFmn7AAQn5AAlmlmg");
	mask.setTransform(0,13);

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.setTransform(0,13);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:1.8},0).wait(1).to({rotation:3.6},0).wait(1).to({rotation:5.4},0).wait(1).to({rotation:7.2},0).wait(1).to({rotation:9},0).wait(1).to({rotation:10.9},0).wait(1).to({rotation:12.7},0).wait(1).to({rotation:14.5},0).wait(1).to({rotation:16.3},0).wait(1).to({rotation:18.1},0).wait(1).to({rotation:19.9},0).wait(1).to({rotation:21.7},0).wait(1).to({rotation:23.5},0).wait(1).to({rotation:25.3},0).wait(1).to({rotation:27.1},0).wait(1).to({rotation:28.9},0).wait(1).to({rotation:30.8},0).wait(1).to({rotation:32.6},0).wait(1).to({rotation:34.4},0).wait(1).to({rotation:36.2},0).wait(1).to({rotation:38},0).wait(1).to({rotation:39.8},0).wait(1).to({rotation:41.6},0).wait(1).to({rotation:43.4},0).wait(1).to({rotation:45.2},0).wait(1).to({rotation:47},0).wait(1).to({rotation:48.8},0).wait(1).to({rotation:50.7},0).wait(1).to({rotation:52.5},0).wait(1).to({rotation:54.3},0).wait(1).to({rotation:56.1},0).wait(1).to({rotation:57.9},0).wait(1).to({rotation:59.7},0).wait(1).to({rotation:61.5},0).wait(1).to({rotation:63.3},0).wait(1).to({rotation:65.1},0).wait(1).to({rotation:66.9},0).wait(1).to({rotation:68.7},0).wait(1).to({rotation:70.6},0).wait(1).to({rotation:72.4},0).wait(1).to({rotation:74.2},0).wait(1).to({rotation:76},0).wait(1).to({rotation:77.8},0).wait(1).to({rotation:79.6},0).wait(1).to({rotation:81.4},0).wait(1).to({rotation:83.2},0).wait(1).to({rotation:85},0).wait(1).to({rotation:86.8},0).wait(1).to({rotation:88.6},0).wait(1).to({rotation:90.5},0).wait(1).to({rotation:92.3},0).wait(1).to({rotation:94.1},0).wait(1).to({rotation:95.9},0).wait(1).to({rotation:97.7},0).wait(1).to({rotation:99.5},0).wait(1).to({rotation:101.3},0).wait(1).to({rotation:103.1},0).wait(1).to({rotation:104.9},0).wait(1).to({rotation:106.7},0).wait(1).to({rotation:108.5},0).wait(1).to({rotation:110.4},0).wait(1).to({rotation:112.2},0).wait(1).to({rotation:114},0).wait(1).to({rotation:115.8},0).wait(1).to({rotation:117.6},0).wait(1).to({rotation:119.4},0).wait(1).to({rotation:121.2},0).wait(1).to({rotation:123},0).wait(1).to({rotation:124.8},0).wait(1).to({rotation:126.6},0).wait(1).to({rotation:128.4},0).wait(1).to({rotation:130.3},0).wait(1).to({rotation:132.1},0).wait(1).to({rotation:133.9},0).wait(1).to({rotation:135.7},0).wait(1).to({rotation:137.5},0).wait(1).to({rotation:139.3},0).wait(1).to({rotation:141.1},0).wait(1).to({rotation:142.9},0).wait(1).to({rotation:144.7},0).wait(1).to({rotation:146.5},0).wait(1).to({rotation:148.3},0).wait(1).to({rotation:150.2},0).wait(1).to({rotation:152},0).wait(1).to({rotation:153.8},0).wait(1).to({rotation:155.6},0).wait(1).to({rotation:157.4},0).wait(1).to({rotation:159.2},0).wait(1).to({rotation:161},0).wait(1).to({rotation:162.8},0).wait(1).to({rotation:164.6},0).wait(1).to({rotation:166.4},0).wait(1).to({rotation:168.2},0).wait(1).to({rotation:170.1},0).wait(1).to({rotation:171.9},0).wait(1).to({rotation:173.7},0).wait(1).to({rotation:175.5},0).wait(1).to({rotation:177.3},0).wait(1).to({rotation:179.1},0).wait(1).to({rotation:180.9},0).wait(1).to({rotation:182.7},0).wait(1).to({rotation:184.5},0).wait(1).to({rotation:186.3},0).wait(1).to({rotation:188.1},0).wait(1).to({rotation:189.9},0).wait(1).to({rotation:191.8},0).wait(1).to({rotation:193.6},0).wait(1).to({rotation:195.4},0).wait(1).to({rotation:197.2},0).wait(1).to({rotation:199},0).wait(1).to({rotation:200.8},0).wait(1).to({rotation:202.6},0).wait(1).to({rotation:204.4},0).wait(1).to({rotation:206.2},0).wait(1).to({rotation:208},0).wait(1).to({rotation:209.8},0).wait(1).to({rotation:211.7},0).wait(1).to({rotation:213.5},0).wait(1).to({rotation:215.3},0).wait(1).to({rotation:217.1},0).wait(1).to({rotation:218.9},0).wait(1).to({rotation:220.7},0).wait(1).to({rotation:222.5},0).wait(1).to({rotation:224.3},0).wait(1).to({rotation:226.1},0).wait(1).to({rotation:227.9},0).wait(1).to({rotation:229.7},0).wait(1).to({rotation:231.6},0).wait(1).to({rotation:233.4},0).wait(1).to({rotation:235.2},0).wait(1).to({rotation:237},0).wait(1).to({rotation:238.8},0).wait(1).to({rotation:240.6},0).wait(1).to({rotation:242.4},0).wait(1).to({rotation:244.2},0).wait(1).to({rotation:246},0).wait(1).to({rotation:247.8},0).wait(1).to({rotation:249.6},0).wait(1).to({rotation:251.5},0).wait(1).to({rotation:253.3},0).wait(1).to({rotation:255.1},0).wait(1).to({rotation:256.9},0).wait(1).to({rotation:258.7},0).wait(1).to({rotation:260.5},0).wait(1).to({rotation:262.3},0).wait(1).to({rotation:264.1},0).wait(1).to({rotation:265.9},0).wait(1).to({rotation:267.7},0).wait(1).to({rotation:269.5},0).wait(1).to({rotation:271.4},0).wait(1).to({rotation:273.2},0).wait(1).to({rotation:275},0).wait(1).to({rotation:276.8},0).wait(1).to({rotation:278.6},0).wait(1).to({rotation:280.4},0).wait(1).to({rotation:282.2},0).wait(1).to({rotation:284},0).wait(1).to({rotation:285.8},0).wait(1).to({rotation:287.6},0).wait(1).to({rotation:289.4},0).wait(1).to({rotation:291.3},0).wait(1).to({rotation:293.1},0).wait(1).to({rotation:294.9},0).wait(1).to({rotation:296.7},0).wait(1).to({rotation:298.5},0).wait(1).to({rotation:300.3},0).wait(1).to({rotation:302.1},0).wait(1).to({rotation:303.9},0).wait(1).to({rotation:305.7},0).wait(1).to({rotation:307.5},0).wait(1).to({rotation:309.3},0).wait(1).to({rotation:311.2},0).wait(1).to({rotation:313},0).wait(1).to({rotation:314.8},0).wait(1).to({rotation:316.6},0).wait(1).to({rotation:318.4},0).wait(1).to({rotation:320.2},0).wait(1).to({rotation:322},0).wait(1).to({rotation:323.8},0).wait(1).to({rotation:325.6},0).wait(1).to({rotation:327.4},0).wait(1).to({rotation:329.2},0).wait(1).to({rotation:331.1},0).wait(1).to({rotation:332.9},0).wait(1).to({rotation:334.7},0).wait(1).to({rotation:336.5},0).wait(1).to({rotation:338.3},0).wait(1).to({rotation:340.1},0).wait(1).to({rotation:341.9},0).wait(1).to({rotation:343.7},0).wait(1).to({rotation:345.5},0).wait(1).to({rotation:347.3},0).wait(1).to({rotation:349.1},0).wait(1).to({rotation:351},0).wait(1).to({rotation:352.8},0).wait(1).to({rotation:354.6},0).wait(1).to({rotation:356.4},0).wait(1).to({rotation:358.2},0).wait(1).to({rotation:360},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122.3,-109.4,244.7,244.8);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 24
	this.slot1 = new lib.Символ30();
	this.slot1.setTransform(-22.3,-417);

	this.timeline.addTween(cjs.Tween.get(this.slot1).wait(1));

	// Слой 6
	this.instance = new lib.Символ28();
	this.instance.setTransform(-22.5,-147.7,1.132,1.132);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 7
	this.instance_1 = new lib.Символ56();
	this.instance_1.setTransform(-14,18.6);
	this.instance_1.alpha = 0.711;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-174.7,-631,304.6,662.6);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.asdgasfhaerfghafh();
	this.instance.setTransform(-211.2,-60);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(3));

	// Слой 1
	this.instance_1 = new lib.Символ6();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},3).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-218.5,-88,437,176);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AmeDaIhwjRIA1g6QAqgZAQgRQAOgQAyASIgDgBIAPgSIA5AAQAAgOAMgGQAagOAqAIIAAAAIAAgOQAKgCAfgBQAHgOATgLQAegRAqAAIADAAIAHgFQAfgUBJABQBMABAvAVQAoASAPAaQAdgHAnAAQApAAAdAHQAcAIACAKQC1AkhIClQisBWkSAOQjSAyj0AAIgUAAg");
	var mask_graphics_59 = new cjs.Graphics().p("AmeDaIhwjRIA1g6QAqgZAQgRQAOgQAyASIgDgBIAPgSIA5AAQAAgOAMgGQAagOAqAIIAAAAIAAgOQAKgCAfgBQAHgOATgLQAegRAqAAIADAAIAHgFQAfgUBJABQBMABAvAVQAoASAPAaQAdgHAnAAQApAAAdAHQAcAIACAKQC1AkhIClQisBWkSAOQjSAyj0AAIgUAAg");
	var mask_graphics_99 = new cjs.Graphics().p("AmeDaIhwjRIA1g6QAqgZAQgRQAOgQAyASIgDgBIAPgSIA5AAQAAgOAMgGQAagOAqAIIAAAAIAAgOQAKgCAfgBQAHgOATgLQAegRAqAAIADAAIAHgFQAfgUBJABQBMABAvAVQAoASAPAaQAdgHAnAAQApAAAdAHQAcAIACAKQC1AkhIClQisBWkSAOQjSAyj0AAIgUAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1,y:0.7}).wait(59).to({graphics:mask_graphics_59,x:1,y:0.7}).wait(40).to({graphics:mask_graphics_99,x:1,y:0.7}).wait(1));

	// Слой 2
	this.instance = new lib.Анимация1("synched",0);
	this.instance.setTransform(-121.2,8.3);

	this.instance_1 = new lib.Анимация2("synched",0);
	this.instance_1.setTransform(137.7,8.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.51,1],-33,0,33,0).s().p("AlJL8IAA34IKTAAIAAX4g");
	this.shape.setTransform(137.7,8.3);

	this.instance.mask = this.instance_1.mask = this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},59).to({state:[{t:this.shape}]},40).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,x:137.7},59).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ5();
	this.instance.setTransform(1.5,-9.5);
	this.instance.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ1();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152.8,-83.1,234.1,166.3);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ41();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57,-84,114,168);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:0.2},0).wait(1).to({y:0.4},0).wait(1).to({y:0.5},0).wait(1).to({y:0.7},0).wait(1).to({y:0.8},0).wait(1).to({y:1},0).wait(1).to({y:1.1},0).wait(1).to({y:1.2},0).wait(1).to({y:1.3},0).wait(1).to({y:1.4},0).wait(1).to({y:1.5},0).wait(1).to({y:1.6},0).wait(1).to({y:1.7},0).wait(1).to({y:1.8},0).wait(1).to({y:1.9},0).wait(2).to({y:2},0).wait(1).to({y:2.1},0).wait(2).to({y:2.2},0).wait(3).to({y:2.3},0).wait(2).to({y:2.4},0).wait(3).to({y:2.5},0).wait(2).to({y:2.3},0).wait(1).to({y:2.2},0).wait(1).to({y:2},0).wait(1).to({y:1.8},0).wait(1).to({y:1.7},0).wait(1).to({y:1.6},0).wait(1).to({y:1.4},0).wait(1).to({y:1.3},0).wait(1).to({y:1.2},0).wait(1).to({y:1.1},0).wait(1).to({y:1},0).wait(1).to({y:0.9},0).wait(1).to({y:0.8},0).wait(1).to({y:0.7},0).wait(2).to({y:0.6},0).wait(1).to({y:0.5},0).wait(2).to({y:0.4},0).wait(2).to({y:0.3},0).wait(2).to({y:0.2},0).wait(3).to({y:0.1},0).wait(3).to({y:0},0).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.5,-38.5,57,77);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(-4.5,29.2,1,1,-5.5,0,0,-4.5,29.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:9.5,y:29.3},29).to({rotation:-5.5,y:29.2},30).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22,-31.2,38.5,61.9);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ35();
	this.instance.setTransform(-11,24.5,1,1,0,0,0,-10,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:0,regY:0,rotation:-0.9,x:-1.4,y:0.3},0).wait(1).to({rotation:-1.7,x:-1.7,y:0.2},0).wait(1).to({rotation:-2.4,x:-2,y:0.1},0).wait(1).to({rotation:-3,x:-2.3,y:0},0).wait(1).to({rotation:-3.6,x:-2.5,y:-0.1},0).wait(1).to({rotation:-4.1,x:-2.7,y:-0.2},0).wait(1).to({rotation:-4.5,x:-2.9},0).wait(1).to({rotation:-5,x:-3.1,y:-0.3},0).wait(1).to({rotation:-5.3,x:-3.3},0).wait(1).to({rotation:-5.7,x:-3.4,y:-0.4},0).wait(1).to({rotation:-6,x:-3.6},0).wait(1).to({rotation:-6.3,x:-3.7,y:-0.5},0).wait(1).to({rotation:-6.6,x:-3.8},0).wait(1).to({rotation:-6.9,x:-4},0).wait(1).to({rotation:-7.2,x:-4.1,y:-0.6},0).wait(1).to({rotation:-7.4,x:-4.2},0).wait(1).to({rotation:-7.6,x:-4.3},0).wait(1).to({rotation:-7.8},0).wait(1).to({rotation:-8,x:-4.4,y:-0.7},0).wait(1).to({rotation:-8.1,x:-4.5},0).wait(1).to({rotation:-8.3},0).wait(1).to({rotation:-8.4,x:-4.6},0).wait(1).to({rotation:-8.5,x:-4.7},0).wait(1).to({rotation:-8.6},0).wait(1).to({rotation:-8.8,x:-4.8,y:-0.8},0).wait(1).to({rotation:-8.9},0).wait(1).to({rotation:-9,x:-4.9},0).wait(1).to({rotation:-9.1},0).wait(1).to({regX:-10,regY:24,rotation:-9.2,x:-10.9,y:24.5},0).wait(1).to({regX:0,regY:0,rotation:-8.3,x:-4.6,y:-0.7},0).wait(1).to({rotation:-7.5,x:-4.2,y:-0.6},0).wait(1).to({rotation:-6.8,x:-3.9,y:-0.5},0).wait(1).to({rotation:-6.2,x:-3.7},0).wait(1).to({rotation:-5.7,x:-3.4,y:-0.4},0).wait(1).to({rotation:-5.2,x:-3.2,y:-0.3},0).wait(1).to({rotation:-4.7,x:-3},0).wait(1).to({rotation:-4.3,x:-2.8,y:-0.2},0).wait(1).to({rotation:-4,x:-2.7,y:-0.1},0).wait(1).to({rotation:-3.6,x:-2.5},0).wait(1).to({rotation:-3.3,x:-2.4,y:0},0).wait(1).to({rotation:-3,x:-2.3},0).wait(1).to({rotation:-2.7,x:-2.1,y:0.1},0).wait(1).to({rotation:-2.4,x:-2},0).wait(1).to({rotation:-2.1,x:-1.9},0).wait(1).to({rotation:-1.9,x:-1.8,y:0.2},0).wait(1).to({rotation:-1.7,x:-1.7},0).wait(1).to({rotation:-1.5,x:-1.6},0).wait(1).to({rotation:-1.3,y:0.3},0).wait(1).to({rotation:-1.2,x:-1.5},0).wait(1).to({rotation:-1,x:-1.4},0).wait(1).to({rotation:-0.9},0).wait(1).to({rotation:-0.8,x:-1.3,y:0.4},0).wait(1).to({rotation:-0.6},0).wait(1).to({rotation:-0.5,x:-1.2},0).wait(1).to({rotation:-0.4},0).wait(1).to({rotation:-0.3,x:-1.1},0).wait(1).to({rotation:-0.2,y:0.5},0).wait(1).to({rotation:-0.1,x:-1},0).wait(1).to({regX:-10,regY:24,rotation:0,x:-11,y:24.5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22,-27.5,42,56);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ36();
	this.instance.setTransform(44,-25.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(-46.5,-44);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 4
	this.instance_2 = new lib.Символ40();
	this.instance_2.setTransform(-8.5,-75);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 1
	this.instance_3 = new lib.Символ42();
	this.instance_3.setTransform(-8,31.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.5,-113.5,132.5,229);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.setTransform(0,0,0.727,0.727);
	this.instance.alpha = 0.852;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-1124.3},39).to({skewY:180,y:79},1).to({x:-97,y:-137},49).to({skewY:0,x:-42,y:222.1},1).to({x:-1033.2,y:-183},49).to({skewY:180,x:-1133.3,y:117.1},1).to({x:-74,y:-12.9},49).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.9,-64,317.8,128);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(23.3,44.2);

	this.instance_1 = new lib.Символ34();
	this.instance_1.setTransform(-28.4,-18.2,0.961,0.961);

	this.instance_2 = new lib.Символ47();
	this.instance_2.setTransform(-29.6,80.3,0.961,0.961);
	this.instance_2.alpha = 0.512;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129.5,-127.3,234.1,254.7);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 3
	this.slot = new lib.Символ25();
	this.slot.setTransform(132.5,27.2,0.764,0.764);

	this.timeline.addTween(cjs.Tween.get(this.slot).to({scaleX:0.84,scaleY:0.84,x:52.5},6).to({scaleX:0.89,scaleY:0.89},3).wait(1).to({scaleX:0.84,scaleY:0.84},3).to({scaleX:0.76,scaleY:0.76,x:132.5},6).wait(1));

	// Слой 2
	this.instance = new lib.Символ50();
	this.instance.setTransform(-240.2,-49.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.09,scaleY:1.09,x:-151.1,y:-53.2},6).to({x:-199.1},3).wait(1).to({x:-151.1},3).to({scaleX:1,scaleY:1,x:-240.2,y:-49.6},6).wait(1));

	// Слой 18
	this.instance_1 = new lib.Символ61();
	this.instance_1.setTransform(-98.2,-115.4,1.334,1.334,-24.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-62.7,y:-131.4},3).to({x:-457.8,y:62.6,alpha:0},6).wait(1).to({x:-62.7,y:-131.4,alpha:1},6).to({x:-98.2,y:-115.4},3).wait(1));

	// Слой 17
	this.instance_2 = new lib.Символ59();
	this.instance_2.setTransform(-93,-158.5,1.724,1,-26.5,0,0,-0.1,-0.1);
	this.instance_2.alpha = 0.641;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:0},9).wait(1).to({alpha:0.641},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-641,-455.1,907.3,601.3);


// stage content:



(lib._600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(link1, "_blank");
		}
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
			_this.main.slot.slot1.gotoAndPlay(172);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(11);
			_this.main.slot.slot1.gotoAndPlay(235);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 1
	this.main = new lib.Символ3();
	this.main.setTransform(340.2,235.2);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// Слой 2
	this.instance = new lib.Символ8();
	this.instance.setTransform(895.5,95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ46();
	this.instance_1.setTransform(299.5,148.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.8,-69.9,1355.1,601.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;